#!/bin/bash

bl=/sys/class/backlight/backlight.12

cur=$(cat $bl/actual_brightness)
max=$(cat $bl/max_brightness)
stp=$(($max / 10))
min=$(($max / 100))

br=$cur
if [ "$1" = "up" ] ; then
    br=$(($cur + $stp))
fi
if [ "$1" = "down" ] ; then
    br=$(($cur - $stp))
fi
if [ "$1" = "max" ] ; then
    br=$max
fi
if [ "$1" = "min" ] ; then
    br=$min
fi

# don't allow black
if [ $br -lt $min ] ; then
    br=$min
fi
# avoid overflow
if [ $br -gt $max ] ; then
    br=$max
fi

echo $br > $bl/brightness
#cat $bl/actual_brightness
